### ISSUE TITLE
No need for uvicorn

### ISSUE THREAD

**Issue by Mte90** [Hybridhash/FastAPI-HTMX#2]
So the readme is incomplete, there are more parameters required.

```
CSRF_SECRET_KEY=123
COOKIE_SAMESITE=none
COOKIE_SECURE=true
```

Removing from the pyproject uvicorn and using `fastapi = {extras = ["standard"], version = "0.115.4"}` let's to use the fastapi server.

poetry run fastapi run ./app/app.py

**Comment by Hybridhash** [comment]
Yes, you are right this is required to be updated in Readme. Let me also update this part for ease of use.
